# trinket_tags.py
trinket_tags = {
    0: "No Trinket",
    1: "T-Bone's Lucky Tie",
    2: "Batterson's Bubble",
    3: "Dark Water Daisy",
    4: "Vote for Cyclops",
    5: "Ramses' Dragon Horn",
    6: "Iris' Iris",
    7: "Kuckoo Kazoo",
    8: "Ramses' Rune",
    9: "Ullysses Uniclops",
    10: "Billy Bison",
    11: "Stealth Elf's Gift",
    12: "Lizard Lilly",
    13: "Pirate Pinwheel",
    14: "Bubble Blower",
    15: "Medal of Heroism",
    16: "Blobber's Medal of Courage",
    17: "Medal of Valiance",
    18: "Medal of Gallantry",
    19: "Medal of Mettle",
    20: "Winged Medal of Bravery",
    21: "Seadog Seashell",
    22: "Snuckles' Sunflower",
    23: "Teddy Cyclops",
    24: "Goo Factory Gear",
    25: "Elemental Opal",
    26: "Elemental Radiant",
    27: "Elemental Diamond",
    28: "Cyclops Spinner",
    29: "Wilikin Windmill",
    30: "Time Town Ticker",
    31: "Big Bow of Boom",
    32: "Mabu's Medallion",
    33: "Spyro's Shield",
}
